import type { ActivePullRequestReview, PullRequestDetail, PullRequestDiffFile, PullRequestTimelineItem } from "@shared/github-types";
import { ExternalLink, RefreshCw, TriangleAlert } from "lucide-react";
import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

type Tab = "overview" | "conversation" | "files" | "checks";
interface Props { projectId: string; remoteName: string; prNumber: number; onReviewOpened(sessionId: string): void; onWorkspaceChanged(): void; }
const message = (error: unknown) => error instanceof Error ? error.message : String(error);
function Markdown({ children }: { children: string }) { return <ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{ a: ({ href, children: content }) => <a href={href} onClick={(event) => { event.preventDefault(); if (href) void window.multiCliWork.shell.openExternal(href); }}>{content}</a> }}>{children}</ReactMarkdown>; }

export function PullRequestDetailView({ projectId, remoteName, prNumber, onReviewOpened, onWorkspaceChanged }: Props) {
  const [detail, setDetail] = useState<PullRequestDetail | null>(null); const [diff, setDiff] = useState<PullRequestDiffFile[] | null>(null);
  const [tab, setTab] = useState<Tab>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [draft, setDraft] = useState(""); const [replyDrafts, setReplyDrafts] = useState<Record<string,string>>({}); const [activeReview, setActiveReview] = useState<ActivePullRequestReview | null>(null);
  const [reviewPrompt, setReviewPrompt] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [next, reviews] = await Promise.all([window.multiCliWork.github.detail(projectId, remoteName, prNumber), window.multiCliWork.github.activeReviews()]); setDetail(next); setActiveReview(reviews.find((review) => review.projectId === projectId && review.remoteName === remoteName && review.pullRequestNumber === prNumber) ?? null); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } };
  useEffect(() => { void load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [projectId, remoteName, prNumber]);
  useEffect(() => { if (tab !== "files" || diff) return; void window.multiCliWork.github.diff(projectId, remoteName, prNumber).then(setDiff).catch((cause) => setError(message(cause))); }, [tab, diff, projectId, remoteName, prNumber]);
  const startReview = async (agent: "claude" | "codex") => { try { const result = await window.multiCliWork.github.startReview(projectId, remoteName, prNumber, agent); setActiveReview(result.review); setReviewPrompt(result.prompt); onWorkspaceChanged(); onReviewOpened(result.session.id); } catch (cause) { setError(message(cause)); } };
  const finish = async (allowUnverifiedReview = false, discardChanges = false): Promise<void> => { if (!activeReview) return; try { const result = await window.multiCliWork.github.finishReview(activeReview.id, { allowUnverifiedReview, discardChanges }); if (result.state === "review-unverified" || result.state === "verification-unavailable") { if (window.confirm(`${result.message}\n그래도 정리하시겠습니까?`)) await finish(true, discardChanges); return; } if (result.state === "dirty") { if (window.confirm(`${result.message}\n변경을 버리고 강제 제거하시겠습니까?`)) await finish(true, true); return; } setActiveReview(null); onWorkspaceChanged(); } catch (cause) { setError(message(cause)); } };
  const timeline = (item: PullRequestTimelineItem) => <article key={`${item.kind}-${item.id}`} id={item.kind === "inline" ? `thread-${item.path}-${item.line ?? item.originalLine ?? 0}` : undefined} className="pr-timeline-item"><header>{item.author.login} · {item.kind === "review" ? item.state : item.kind === "inline" ? <button type="button" className="pr-inline-link" onClick={() => { setTab("files"); window.setTimeout(() => document.getElementById(`diff-${item.path}`)?.scrollIntoView({ block: "start" }), 0); }}>{item.path}:{item.line ?? item.originalLine ?? "?"}</button> : "댓글"}</header><Markdown>{item.body}</Markdown>{item.kind === "inline" ? <form onSubmit={(event) => { event.preventDefault(); const body = replyDrafts[item.id]?.trim(); if (!body) return; void window.multiCliWork.github.reply(projectId, remoteName, prNumber, item.id, body).then(() => { setReplyDrafts((current) => ({ ...current, [item.id]: "" })); return load(); }).catch((cause) => setError(message(cause))); }}><textarea aria-label={`${item.id} 답글`} value={replyDrafts[item.id] ?? ""} onChange={(event) => setReplyDrafts((current) => ({ ...current, [item.id]: event.target.value }))}/><button type="submit">답글</button></form> : null}</article>;
  if (loading && !detail) return <div className="pr-detail-empty">PR을 불러오는 중…</div>;
  if (!detail) return <div className="pr-detail-empty" role="alert">{error ?? "PR을 열 수 없습니다"}</div>;
  return <section className="pr-detail" aria-label={`PR #${prNumber} 상세`}>
    <header className="pr-detail-header"><div><small>#{detail.number} · {detail.state}{detail.isDraft ? " · Draft" : ""}</small><h2>{detail.title}</h2><span>{detail.author} · {detail.baseRefName} ← {detail.headRefName} · {detail.headRefOid.slice(0,7)}</span></div><div className="pr-detail-actions"><button type="button" aria-label="웹에서 열기" onClick={() => void window.multiCliWork.shell.openExternal(detail.url)}><ExternalLink size={14}/></button><button type="button" aria-label="PR 새로고침" onClick={() => void load()}><RefreshCw size={14}/></button>{activeReview ? <><button type="button" onClick={() => onReviewOpened(activeReview.sessionId)}>진행 중 리뷰 열기</button>{!activeReview.promptDelivered ? <><button type="button" onClick={() => void window.multiCliWork.github.refillReview(activeReview.id).catch((cause) => setError(message(cause)))}>다시 채우기</button>{reviewPrompt ? <button type="button" onClick={() => void window.multiCliWork.clipboard.writeText(reviewPrompt)}>복사</button> : null}</> : null}<button type="button" onClick={() => void finish()}>리뷰 완료</button></> : <><button type="button" onClick={() => void startReview("claude")}>Claude Code 리뷰</button><button type="button" onClick={() => void startReview("codex")}>Codex 리뷰</button></>}</div></header>
    {error ? <div className="action-error" role="alert"><TriangleAlert size={14}/><span>{error}</span></div> : null}
    <nav className="pr-detail-tabs" role="tablist">{(["overview","conversation","files","checks"] as Tab[]).map((value) => <button type="button" role="tab" aria-selected={tab === value} key={value} onClick={() => setTab(value)}>{{overview:"개요",conversation:"대화·리뷰",files:`변경 파일 (${detail.files.length})`,checks:`체크 (${detail.checks.length})`}[value]}</button>)}</nav>
    <div className="pr-detail-body">{tab === "overview" ? <><div className="pr-labels">{detail.labels.map((label) => <span key={label}>{label}</span>)}</div><div className="file-viewer-markdown"><Markdown>{detail.body || "본문이 없습니다."}</Markdown></div><h3>커밋</h3>{detail.commits.map((commit) => <div className="pr-commit" key={commit.oid}><code>{commit.oid.slice(0,7)}</code> {commit.message}</div>)}</> : tab === "conversation" ? <><form className="pr-comment-form" onSubmit={(event) => { event.preventDefault(); if (!draft.trim()) return; void window.multiCliWork.github.comment(projectId, remoteName, prNumber, draft.trim()).then(() => { setDraft(""); return load(); }).catch((cause) => setError(message(cause))); }}><textarea aria-label="새 PR 댓글" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="댓글 추가"/><button type="submit">댓글 게시</button></form>{detail.timeline.map(timeline)}</> : tab === "files" ? diff?.map((file) => <article className="pr-diff-file" key={file.path} id={`diff-${file.path}`}><h3>{file.path}{file.truncated ? " · 잘림" : ""}</h3><pre>{file.patch}</pre></article>) ?? <div>diff 불러오는 중…</div> : detail.checks.map((check) => <div className="pr-check" key={`${check.name}-${check.detailsUrl}`}><strong>{check.name}</strong><span>{check.state} · {check.conclusion ?? "진행 중"}</span></div>)}</div>
  </section>;
}
